### ISSUE TITLE
Regexp not working correctly for Windows Batch files

### ISSUE THREAD

**Issue by xdml** [s3rvac/AutoFenc#2]
Comment regexp does not work correctly for comments in Windows Batch files (file extensions `.bat` and `.cmd`). Comments starts with keyword `rem`. If keyword `rem` starts at beginning of line, the regexp does not work. If I add a space in front of it, it works as expected, but looks ugly.

The comment regexp is too complicated for me, so I am not able to parse it my self, so I am sorry for not providing you with pull request.

This does not work:

``` batch
rem vim: fileencoding=cp852
```

This works:

``` batch
 rem vim: fileencoding=cp852
```

**Comment by s3rvac** [comment]
Thank you for your report! The problem was indeed in the comment regexp. I have fixed it in commit 436176ac3d486e597ecb11d98f9b045286b18fdb. The the detection now works even when there is no space before `rem`.
